15-y-nakamura/SalesManagement_SysDev

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShainKanri.cs
SalesManagement_SysDev/TopHonshaPage.cs

ボタンとNameとエラー

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShainKanri.cs
SalesManagement_SysDev/ShohinKanri.Designer.cs
SalesManagement_SysDev/TopButsuryuPage.Designer.cs
SalesManagement_SysDev/TopEigyoPage.Designer.cs
SalesManagement_SysDev/TopHonshaPage.Designer.cs

各フォームのレイアウトの統一

---

SalesManagement_SysDev/TopButsuryuPage.Designer.cs
SalesManagement_SysDev/TopEigyoPage.Designer.cs
SalesManagement_SysDev/TopHonshaPage.Designer.cs
SalesManagement_SysDev/TopHonshaPage.cs

・画面遷移ボタンのプログラムを少し変更show→showDialog（Top本社）
・フォームのプロパティ　動作＞データの転記DoubleBuffered をtrueに変更（Top本社・Top物流・Top営業）

画面遷移ボタン少し変更

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShohinKanri.Designer.cs

"全画面のデータグリッドビューの名前変更"と"商品管理画面にてshouhinIdからshouhinnameに変更"

"全画面のデータグリッドビューの名前変更"と"商品管理画面にてshouhinIdからshouhinnameに変更"

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShohinKanri.Designer.cs

営業所名をコンボボックスに変更

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj

形式チェックのための共通モジュールクラスInputCheckを作成しました
共通モジュールクラスを格納するためのCommonファイルを作成しました
InputCheckの中に数個のモジュールを作成しました

共通モジュールクラスInputCheckの追加、Commonファイルの作成

---

SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj

クラスの作成・ログインに必要なデータアクセスのモジュール作成・データアクセスファイルの作成

クラスの作成・ログインに必要なデータアクセスのモジュール作成・データアクセスファイルの作成

---

SalesManagement_SysDev/ChumonKanri.Designer.cs

注文管理画面の一覧表示ボタン削除

---

SalesManagement_SysDev/M_Message.cs
SalesManagement_SysDev/MessageDsp.cs
SalesManagement_SysDev/SalesManagement_DevContext.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj

メッセージ一覧を表示するためのプログラム

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShohinKanri.Designer.cs
SalesManagement_SysDev/TopButsuryuPage.Designer.cs
SalesManagement_SysDev/TopEigyoPage.Designer.cs
SalesManagement_SysDev/TopHonshaPage.Designer.cs

上のラベルの位置調整

---

SalesManagement_SysDev/ChumonKanri.Designer.cs

注文管理画面の注文状態フラグ削除
注文管理フラグと非表示理由の位置調整

注文管理画面の注文状態フラグ削除

---

SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/ShainKanri.cs

テキストボックス内の灰色の文字のコード、コメント追加

---

SalesManagement_SysDev/Common/InputCheck.cs

inputcheckのコメント誤字訂正

---

SalesManagement_SysDev/LoginPage.Designer.cs
SalesManagement_SysDev/LoginPage.cs

システム終了処理の作成

---

SalesManagement_SysDev/PasswordChangePage.Designer.cs
SalesManagement_SysDev/PasswordChangePage.cs
SalesManagement_SysDev/PasswordChangePage.resx
SalesManagement_SysDev/SalesManagement_SysDev.csproj
SalesManagement_SysDev/ShainKanri.Designer.cs

パスワード変更画面作成・社員管理のパスワード削除

---

SalesManagement_SysDev/ShainKanri.Designer.cs

社員管理画面のテキストボックスとコンボボックスの誤字訂正

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/LoginPage.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShainKanri.cs
SalesManagement_SysDev/ShohinKanri.Designer.cs
SalesManagement_SysDev/ShohinKanri.cs
SalesManagement_SysDev/TopButsuryuPage.Designer.cs
SalesManagement_SysDev/TopButsuryuPage.cs
SalesManagement_SysDev/TopEigyoPage.Designer.cs
SalesManagement_SysDev/TopEigyoPage.cs
SalesManagement_SysDev/TopHonshaPage.Designer.cs
SalesManagement_SysDev/TopHonshaPage.cs

役割によって押せるボタン、押せないボタンの作成

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/DataAccess/PositionDataAccess.cs
SalesManagement_SysDev/DataAccess/SalesOfficeDataAccess.cs
SalesManagement_SysDev/Entity/M_Employee.cs
SalesManagement_SysDev/Entity/M_MajorClassification.cs
SalesManagement_SysDev/Entity/M_Message.cs
SalesManagement_SysDev/MessageDsp.cs
SalesManagement_SysDev/Program.cs
SalesManagement_SysDev/SalesManagement_DevContext.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShainKanri.cs

役職テーブルアクセス用のクラス「PositionDataAccess」を追加しました。
営業所テーブルアクセス用のクラス「SalesOfficeDataAccess」を追加しました。
ShainKanriに社員登録機能に関するモジュールを追加しました。
InputCheckに社員登録機能に関するモジュールを追加しました。
EmployeeDataAccessに社員登録機能と社員一覧表示機能に関するモジュールを追加しました。
M_Employeeに社員一覧表示機能に関するモジュールを追加しました。
M_Messageの保存場所を変更し、一部コードを修正しました。

クラスの追加、InputCheckのモジュール追加、DB設定の変更、社員登録機能の追加

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj
SalesManagement_SysDev/TopButsuryuPage.Designer.cs
SalesManagement_SysDev/ZaikoKanri.Designer.cs
SalesManagement_SysDev/ZaikoKanri.cs
SalesManagement_SysDev/ZaikoKanri.resx

在庫管理作成、Form間の移動の処理追加

---

SalesManagement_SysDev/NyukaKanri.Designer.cs
SalesManagement_SysDev/NyukaKanri.cs
SalesManagement_SysDev/NyukoKanri.Designer.cs
SalesManagement_SysDev/NyukoKanri.cs
SalesManagement_SysDev/ShukkaKanri.Designer.cs
SalesManagement_SysDev/ShukkaKanri.cs
SalesManagement_SysDev/ShukkoKanri.Designer.cs
SalesManagement_SysDev/ShukkoKanri.cs
SalesManagement_SysDev/TopButsuryuPage.Designer.cs
SalesManagement_SysDev/TopButsuryuPage.cs
SalesManagement_SysDev/TopEigyoPage.Designer.cs
SalesManagement_SysDev/TopEigyoPage.cs

在庫、入庫、出庫、入荷、出荷の画面レイアウトをチェックしました。
Nameやツールの修正を行いました。
ボタンを押して行き来できるようにしました。

画面レイアウトチェック

---

SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/ClientDataAcces.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/Entity/M_Client.cs
SalesManagement_SysDev/JuchuKanri.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/LoginPage.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShainKanri.cs
SalesManagement_SysDev/ShohinKanri.cs
SalesManagement_SysDev/TopButsuryuPage.cs
SalesManagement_SysDev/TopEigyoPage.cs
SalesManagement_SysDev/TopHonshaPage.cs

顧客の登録機能の作成

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/ClientDataAcces.cs
SalesManagement_SysDev/Entity/M_Client.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/TopEigyoPage.cs

顧客の更新機能の作成

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/ShainKanri.cs

社員管理_更新の疑似言語を提出フォルダにて作成しました。
社員管理_登録のテストと入力チェックのプログラムを修正しました。

疑似言語作成と、テストとプログラム修正

---

SalesManagement_SysDev/Kokyakukanri.cs

クリックされた行をテキストボックスに入れる処理

---

SalesManagement_SysDev/Kokyakukanri.cs

顧客管理フラグを日本語に変換する処理の作成

---

SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShainKanri.cs

灰色の文字を表示・非表示する処理

---

SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/ShainKanri.cs

社員検索機能の実装（完成）

---

SalesManagement_SysDev/DataAccess/ClientDataAcces.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs

顧客の非表示と画面更新

---

SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/HachuKanri.cs
SalesManagement_SysDev/JuchuKanri.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/LoginPage.cs
SalesManagement_SysDev/NyukaKanri.cs
SalesManagement_SysDev/NyukoKanri.cs
SalesManagement_SysDev/ShainKanri.Designer.cs
SalesManagement_SysDev/ShainKanri.cs
SalesManagement_SysDev/ShohinKanri.cs
SalesManagement_SysDev/ShukkaKanri.cs
SalesManagement_SysDev/ShukkoKanri.cs
SalesManagement_SysDev/TopButsuryuPage.cs
SalesManagement_SysDev/TopEigyoPage.cs
SalesManagement_SysDev/TopHonshaPage.cs
SalesManagement_SysDev/UriageKanri.cs
SalesManagement_SysDev/ZaikoKanri.cs

社員管理に関するモジュールの詳細コメントがついていないところにコメントを追加しました。
その他、社員検索時の不具合を修正しました。

モジュールのコメントを更新

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/MajorClassificationDataAccess.cs
SalesManagement_SysDev/DataAccess/ProductDataAccess.cs
SalesManagement_SysDev/DataAccess/SalesOfficeDataAccess.cs
SalesManagement_SysDev/DataAccess/SmallClassificationDataAccess.cs
SalesManagement_SysDev/Entity/M_Product.cs
SalesManagement_SysDev/Kokyakukanri.Designer.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj
SalesManagement_SysDev/ShohinKanri.Designer.cs
SalesManagement_SysDev/ShohinKanri.cs
SalesManagement_SysDev/ShohinKanri.resx

商品管理 登録・更新機能

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/Kokyakukanri.cs

顧客更新時の入力チェック順変更

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/ShainKanri.cs

社員管理の更新、検索の修正

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/ClientDataAcces.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/LoginPage.cs

顧客の検索機能の変更

---

SalesManagement_SysDev/DataAccess/ClientDataAcces.cs

顧客検索の非表示の場合の変更

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/ChumonDataAccess.cs
SalesManagement_SysDev/DataAccess/ChumonDetailDataAccess.cs
SalesManagement_SysDev/ShainKanri.cs

注文管理の検索機能に関するモジュールを作成しました
InpuCheckを一部修正しました。

注文管理の検索機能の実装

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/ChumonDataAccess.cs
SalesManagement_SysDev/DataAccess/ChumonDetailDataAccess.cs
SalesManagement_SysDev/DataAccess/StockDataAccess.cs
SalesManagement_SysDev/DataAccess/SyukkoDataAccess.cs
SalesManagement_SysDev/DataAccess/SyukkoDetailDataAccess.cs
SalesManagement_SysDev/SalesManagement_SysDev.csproj

注文管理の確定機能に関するモジュールを作成しました。
それに伴いStockDataAccess、SyukkoDataAccess、SyukkoDetailDataAccessクラスを作成しました

注文管理の確定機能実装

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/ChumonDataAccess.cs
SalesManagement_SysDev/DataAccess/ChumonDetailDataAccess.cs
SalesManagement_SysDev/DataAccess/ClientDataAcces.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/DataAccess/ShohinDataAccess.cs

・メッセージ表示エラーの修正
・受注IDで検索したときに正しく表示されない不具合を修正
・商品IDで検索したときに正しく表示されない不具合を修正
・フラグで検索したときに正しく表示されない不具合を修正
・商品ID、社員ID、顧客IDを入力したときに対応した名前を表示する機能を追加

注文管理の不具合を修正、他機能の追加

---

SalesManagement_SysDev/ChumonKanri.Designer.cs
SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/SyukkoDataAccess.cs
SalesManagement_SysDev/DataAccess/SyukkoDetailDataAccess.cs
SalesManagement_SysDev/Entity/T_Syukko.cs
SalesManagement_SysDev/Entity/T_SyukkoDetail.cs
SalesManagement_SysDev/ShukkoKanri.Designer.cs
SalesManagement_SysDev/ShukkoKanri.cs

・注文管理の非表示機能の不具合を修正
・出庫管理の初期設定を追加

注文管理の不具合修正

---

SalesManagement_SysDev/LoginPage.Designer.cs
SalesManagement_SysDev/LoginPage.cs

パスワードの非表示とボタンの透明化

---

SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/DataAccess/ChumonDataAccess.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/LoginPage.cs
SalesManagement_SysDev/PasswordChangePage.Designer.cs
SalesManagement_SysDev/PasswordChangePage.cs
SalesManagement_SysDev/ShainKanri.cs

パスワード変更機能の実装
注文管理の確定、非表示機能で注文状態フラグが対応していないときにメッセージを表示するように修正

パスワード変更機能の実装、注文管理の修正

---

SalesManagement_SysDev/ChumonKanri.cs
SalesManagement_SysDev/DataAccess/OrderDataAccess.cs
SalesManagement_SysDev/DataAccess/OrderDetailDataAccess.cs
SalesManagement_SysDev/Entity/T_Order.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.cs
SalesManagement_SysDev/Kokyakukanri.cs
SalesManagement_SysDev/Program.cs
SalesManagement_SysDev/ShainKanri.cs
SalesManagement_SysDev/ShohinKanri.cs

受注管理の検索機能実装
データグリットビューでセルがないときにクリックするとエラー出る不具合を修正

受注管理の検索機能実装、データグリットビューの修正

---

SalesManagement_SysDev/DataAccess/ChumonDataAccess.cs
SalesManagement_SysDev/DataAccess/ChumonDetailDataAccess.cs
SalesManagement_SysDev/DataAccess/OrderDataAccess.cs
SalesManagement_SysDev/DataAccess/OrderDetailDataAccess.cs
SalesManagement_SysDev/DataAccess/ProductDataAccess.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.cs

受注検索の修正、データグリットビューに正しく表示されない不具合を修正、合計金額が商品、価格によって自動で計算する機能を実装、注文管理のデータグリットビューに表示されるデフォルトが処理受付、表示になるように修正

受注管理の検索機能の修正、その他機能実装、修正

---

SalesManagement_SysDev/DataAccess/ChumonDetailDataAccess.cs
SalesManagement_SysDev/DataAccess/EmployeeDataAccess.cs
SalesManagement_SysDev/DataAccess/OrderDataAccess.cs
SalesManagement_SysDev/JuchuKanri.cs
SalesManagement_SysDev/ShainKanri.cs

受注管理のセルクリック時にうまく表示されない不具合を修正
受注管理の確定の修正
注文管理の確定の修正
社員管理の検索で役職名で検索できるように改善

受注管理の修正、注文管理の修正、社員管理の修正

---

SalesManagement_SysDev/Common/InputCheck.cs
SalesManagement_SysDev/DataAccess/ChumonDataAccess.cs
SalesManagement_SysDev/DataAccess/ChumonDetailDataAccess.cs
SalesManagement_SysDev/DataAccess/ProductDataAccess.cs
SalesManagement_SysDev/DataAccess/StockDataAccess.cs
SalesManagement_SysDev/Entity/T_Stock.cs
SalesManagement_SysDev/HachuKanri.cs
SalesManagement_SysDev/JuchuKanri.Designer.cs
SalesManagement_SysDev/JuchuKanri.cs
SalesManagement_SysDev/NyukaKanri.Designer.cs
SalesManagement_SysDev/NyukaKanri.cs
SalesManagement_SysDev/NyukoKanri.Designer.cs
SalesManagement_SysDev/NyukoKanri.cs
SalesManagement_SysDev/ShohinKanri.cs
SalesManagement_SysDev/ShukkaKanri.Designer.cs
SalesManagement_SysDev/ShukkaKanri.cs
SalesManagement_SysDev/ShukkoKanri.cs
SalesManagement_SysDev/TopButsuryuPage.cs
SalesManagement_SysDev/TopEigyoPage.cs
SalesManagement_SysDev/ZaikoKanri.Designer.cs
SalesManagement_SysDev/ZaikoKanri.cs

在庫管理のデータグリットビュー表示
一部管理画面で権限が付与されていない管理画面に移動できてしまう不具合を修正
商品検索が正しく動かない不具合を修正

在庫管理のデータグリットビュー表示、その他修正
